[project]
name = "fraud-detection-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.3",
    "boto3>=1.42.44",
    "psycopg2-binary>=2.9.11",
    "pyspark>=4.1.1",
    "sqlalchemy>=2.0.46",
]
